#!/usr/bin/perl

##############################################################################
##
## Remove the git hash string from the $Hash$ tag in a source file.
## This is used in the "clean" filter when checking a file into a git repo.
##
##############################################################################

while (<>) {

    # Strip everything after $Hash up to the "closing" dollar sign.
    s{\$Hash[^\$]*\$(;?)}{\$Hash\$$1};

    print;

}
